
name = "jobport"
compatibility_date = "2024-09-07"

[build]
command = "npm install && node build.js"
cwd = "."

[build.environment]
NODE_VERSION = "18"
VITE_API_BASE_URL = "https://projectnow.onrender.com"

[assets]
directory = "./dist"

[env.production.vars]
BACKEND_URL = "https://projectnow.onrender.com"
